module.exports = async function () {
  return [
    {
      _rev: 'duvWDRDWsCy2nwSYrrsTnShf7WT080',
      batchFermentablesLocal: [],
      _created: {
        _seconds: 1600564216,
        _nanoseconds: 345000000,
      },
      _timestamp: {
        _seconds: 1603105211,
        _nanoseconds: 188000000,
      },
      measuredOg: 1.063,
      estimatedRbRatio: 0.97,
      measuredEfficiency: 73.71,
      cost: {
        hops: 0,
        hopsShare: 0,
        miscs: 0,
        fermentables: 0,
        perBottlingLiter: 0,
        yeasts: 0,
        yeastsShare: 0,
        total: 0,
        miscsShare: 0,
        fermentablesShare: 0,
      },
      bottlingDate: 1601770204911,
      estimatedColor: 7,
      brewControllerEnabled: false,
      _version: '2.4.7',
      batchMiscs: [
        {
          unit: 'g',
          totalCost: 0,
          inventoryUnit: 'g',
          name: 'Gypsum (CaSO4)',
          timeIsDays: false,
          waterAdjustment: true,
          notInRecipe: false,
          displayAmount: 13,
          amount: 13,
          time: null,
          type: 'Water Agent',
          _id: 'default-1f88df',
          inventory: 0,
          costPerAmount: 0,
          use: 'Mash',
        },
        {
          time: null,
          waterAdjustment: true,
          inventory: 0,
          unit: 'ml',
          _id: 'default-07adb1',
          timeIsDays: false,
          totalCost: 0,
          costPerAmount: 0,
          type: 'Water Agent',
          name: 'Lactic Acid',
          inventoryUnit: 'ml',
          use: 'Mash',
          amount: 4,
          displayAmount: 4,
          notInRecipe: false,
        },
      ],
      measuredFg: 1.012,
      batchMiscsLocal: [],
      measuredKettleEfficiency: 78.82,
      carbonationForce: 10.8,
      measuredAttenuation: 80.1,
      estimatedOg: 1.063,
      batchNo: 18,
      fermentationControllerEnabled: false,
      estimatedBuGuRatio: 0.94,
      notes: [
        {
          note: '',
          timestamp: 1602334851980,
          status: 'Completed',
          type: 'statusChanged',
        },
        {
          type: 'statusChanged',
          note: '',
          status: 'Conditioning',
          timestamp: 1601779325183,
        },
        {
          status: 'Fermenting',
          type: 'statusChanged',
          timestamp: 1601779318238,
          note: '',
        },
        {
          timestamp: 1601442989744,
          note: 'Moved to kegerator to cold crash.',
          status: 'Brewing',
        },
        {
          status: 'Brewing',
          timestamp: 1601189808135,
          note: 'Added dry hops',
        },
        {
          timestamp: 1600570237590,
          status: 'Brewing',
          note: 'Moved 20g of dry hop to a 85C hop stand.',
        },
        {
          note:
            'Ended up with 29L (one extra) pre-boil volume, so boiled off ~0.5L before starting the boil timer to (kinda) compensate.',
          timestamp: 1600565518006,
          status: 'Brewing',
        },
        {
          timestamp: 1600564215083,
          note: '',
          status: 'Brewing',
          type: 'statusChanged',
        },
      ],
      measuredKettleSize: 25.5,
      brewDate: 1600564204911,
      recipe: {
        _id: '8HCh4IpkGSHVOHFJRT9eKUDhr5jOLm',
        boilSize: 28,
        styleFg: true,
        ogPlato: 15.7,
        og: 1.064105873,
        fg: 1.011,
        yeasts: [
          {
            maxTemp: 23.3,
            userNotes: '',
            name: 'US West Coast Yeast',
            maxAbv: null,
            bestBeforeDate: null,
            amount: 1,
            unit: 'pkg',
            starterSize: null,
            form: 'Dry',
            manufacturingDate: 1598412622843,
            description: '',
            starter: false,
            laboratory: "Mangrove Jack's",
            minAttenuation: null,
            attenuation: 82,
            flocculation: 'Medium',
            productId: 'M44',
            maxAttenuation: null,
            fermentsAll: false,
            _id: 'default-fc2796',
            type: 'Ale',
            starterGramExtract: null,
            minTemp: 15,
          },
        ],
        styleConformity: true,
        _created: {
          _seconds: 1599708148,
          _nanoseconds: 9000000,
        },
        miscs: [
          {
            time: null,
            amount: 13,
            use: 'Mash',
            timeIsDays: false,
            waterAdjustment: true,
            name: 'Gypsum (CaSO4)',
            _id: 'default-1f88df',
            unit: 'g',
            type: 'Water Agent',
          },
          {
            _id: 'default-07adb1',
            waterAdjustment: true,
            time: null,
            use: 'Mash',
            name: 'Lactic Acid',
            timeIsDays: false,
            concentration: 85,
            type: 'Water Agent',
            amount: 4,
            unit: 'ml',
          },
        ],
        equipment: {
          mashEfficiency: 78.3,
          bottlingVolume: 21,
          name: 'Grainfather',
          evaporationRate: 0.10714285714285714,
          grainAbsorptionRate: 0.8,
          fermenterLoss: 2,
          fermenterVolumeBeforeTopUp: 23,
          _version: '2.3.0',
          batchSize: 23,
          mashWaterFormula: '(GrainAmountKg * WaterGrainRatio) + MashTunDeadSpaceL',
          _id: 'default-gf23',
          spargeWaterFormula:
            'BoilVolumeColdL - MashWaterL + (GrainAmountKg * GrainAbsorptionRate) + MashTunLossL',
          aromaHopUtilization: 0.23,
          fermenterLossEstimate: 0,
          hopUtilization: 1,
          fermenterVolume: 23,
          _timestamp_ms: 1592619686267,
          trubChillerLoss: 1,
          mashTunLoss: 0,
          spargeWaterOverflow: 'Top-Up',
          hopstandTemperature: 80,
          calcMashEfficiency: true,
          _created: {
            _seconds: 1592619686,
            _nanoseconds: 267000000,
          },
          mashWaterMax: 30,
          mashTunDeadSpace: 3.5,
          boilSize: 28,
          _timestamp: {
            _seconds: 1592619686,
            _nanoseconds: 267000000,
          },
          calcBoilVolume: true,
          boilOffPerHr: 3,
          _rev: 'm1hvhDZFHMhhDL7VSy9s3SqHecyakk',
          calcAromaHopUtilization: true,
          waterGrainRatio: 2.7,
          boilTime: 60,
          waterCalculation: 'Default_2',
          efficiencyType: 'Fermenter',
          postBoilKettleVol: 25,
          mashWaterVolumeLimitEnabled: true,
          efficiency: 75,
        },
        _version: '2.4.3',
        carbonation: 2.4,
        primaryTemp: 20,
        hopsTotalAmount: 200,
        _type: 'recipe',
        name: 'Bell’s Two Hearted Ale',
        searchTags: [],
        mashEfficiency: 78.3,
        _rev: 'TEpaNye1hidCjmYTRDlvJ5xs497G0p',
        style: {
          ibuMin: 40,
          fgMax: 1.014,
          _id: 'default-65',
          fgMin: 1.008,
          type: 'IPA',
          styleGuide: 'BJCP 2015',
          abvMax: 7.5,
          lovibondMin: 6,
          abvMin: 5.5,
          rbrMin: 0.66,
          colorMax: 14,
          buGuMax: 1.11,
          buGuMin: 0.63,
          ogMin: 1.056,
          colorMin: 6,
          carbonationStyle: '21A',
          rbrMax: 1.17,
          ibuMax: 70,
          categoryNumber: '21',
          ogMax: 1.07,
          lovibondMax: 14,
          name: 'American IPA',
          category: 'IPA',
          styleLetter: 'A',
        },
        styleColor: true,
        rbRatio: 0.97,
        postBoilGravity: 1.064105873,
        ibuFormula: 'tinseth',
        _timestamp_ms: 1600564204577,
        firstWortGravity: null,
        ibu: 58.8,
        _public: false,
        preBoilGravity: 1.057,
        public: false,
        buGuRatio: 0.92,
        styleBuGu: true,
        water: {
          spargeTargetDiff: {
            soClRatio: -7.67,
            sulfate: -237.9,
            magnesium: -8.56,
            alkalinity: 15.5698,
            residualAlkalinityMeqLCalc: 2.06258,
            ionBalance: 1,
            bicarbonateMeqL: 0.311393732791399,
            ionBalanceOff: true,
            hardness: -263,
            residualAlkalinity: 85.74638,
            bicarbonate: 19,
            sodium: 30.6,
            anions: -3.767,
            cations: -3.924,
            chloride: 31,
            calcium: -91.2,
          },
          sparge: {
            sulfate: 37.1,
            bicarbonateMeqL: 0.8522354792185657,
            _timestamp_ms: 1579604055529,
            sodium: 46.6,
            hardness: 86,
            type: 'source',
            ionBalance: -1,
            _created: {
              _seconds: 1570932300,
              _nanoseconds: 775000000,
            },
            alkalinity: 42.612,
            ph: '7.4',
            ionBalanceOff: true,
            _timestamp: {
              _seconds: 1579604055,
              _nanoseconds: 529000000,
            },
            calcium: 18.8,
            residualAlkalinityMeqLCalc: 0.37846,
            magnesium: 9.44,
            _version: '1.10.1',
            cations: 3.742,
            _rev: 'Rg52cM1Abxgb3eb9xs4N4RdielBPgJ',
            bicarbonate: 52,
            soClRatio: 0.46,
            anions: 3.909,
            residualAlkalinity: 23.63338,
            _id: 'NLjcLatA9F4swsYcOdHIw7VfeL1VFx',
            chloride: 81,
            name: 'Adelaide (Cumberland Park)',
          },
          mashTargetDiff: {
            ionBalance: -1,
            magnesium: -8.56,
            bicarbonateMeqL: 0.311393732791399,
            chloride: 31,
            sulfate: 117.846,
            hardness: 108,
            anions: 3.639,
            soClRatio: 3.8,
            calcium: 57.299,
            alkalinity: 15.5698,
            sodium: 30.6,
            bicarbonate: 19,
            cations: 3.486,
            ionBalanceOff: true,
            residualAlkalinityMeqLCalc: -0.58403,
            residualAlkalinity: -20.32645,
          },
          enableSpargeAdjustments: false,
          totalTargetDiff: {
            anions: 0.968,
            calcium: 3.731,
            sulfate: -10.482,
            residualAlkalinity: 17.93717,
            ionBalanceOff: true,
            bicarbonateMeqL: 0.311393732791399,
            ionBalance: -4,
            soClRatio: -0.34,
            hardness: -26,
            cations: 0.813,
            residualAlkalinityMeqLCalc: 0.37068,
            magnesium: -8.56,
            alkalinity: 15.5698,
            chloride: 31,
            sodium: 30.6,
            bicarbonate: 19,
          },
          mashPhDistilled: 5.66,
          mashAdjustments: {
            calciumChloride: null,
            magnesiumChloride: 0,
            sodiumMetabisulfitePPM: 0,
            calcium: 148.499,
            sodiumChloride: 0,
            chloride: 0,
            acids: [
              {
                concentration: '85',
                alkalinityMeqL: -2.8923257529734463,
                amount: 4,
                type: 'lactic',
              },
            ],
            sodium: 0,
            magnesium: 0,
            calciumCarbonate: 0,
            sodiumMetabisulfite: 0,
            bicarbonate: 0,
            magnesiumSulfate: 0,
            calciumSulfate: 13,
            calciumHydroxide: 0,
            sodiumBicarbonate: null,
            volume: 20.38,
            sulfate: 355.746,
          },
          spargeWaterAmount: null,
          totalAdjustments: {
            magnesiumChloride: 0,
            calcium: 94.931,
            sodium: 0,
            magnesiumSulfate: 0,
            acids: [
              {
                concentration: '85',
                type: 'lactic',
                amount: 4,
                alkalinityMeqL: -2.8923257529734463,
              },
            ],
            sodiumBicarbonate: null,
            magnesium: 0,
            calciumCarbonate: 0,
            chloride: 0,
            volume: 31.88,
            calciumChloride: null,
            calciumHydroxide: 0,
            bicarbonate: 0,
            calciumSulfate: 13,
            sodiumMetabisulfitePPM: 0,
            sulfate: 227.418,
            sodiumChloride: 0,
            sodiumMetabisulfite: 0,
          },
          spargeAdjustments: {
            calcium: 0,
            sulfate: 0,
            magnesium: 0,
            bicarbonate: 0,
            acids: [
              {
                type: 'lactic',
                concentration: '85',
                amount: 0,
              },
            ],
            volume: 11.5,
            chloride: 0,
            sodiumMetabisulfitePPM: 0,
            sodium: 0,
          },
          acidPhAdjustment: -0.23905,
          enableAcidAdjustments: true,
          sourceTargetDiff: {
            magnesium: -8.56,
            chloride: 31,
            bicarbonate: 19,
            sulfate: -237.9,
            alkalinity: 15.5698,
            residualAlkalinity: 85.74638,
            anions: -3.767,
            sodium: 30.6,
            calcium: -91.2,
            cations: -3.924,
            ionBalanceOff: true,
            residualAlkalinityMeqLCalc: 2.06258,
            soClRatio: -7.67,
            hardness: -263,
            bicarbonateMeqL: 0.311393732791399,
            ionBalance: 1,
          },
          source: {
            _version: '1.10.1',
            chloride: '81',
            magnesium: '9.44',
            cations: 3.742,
            anions: 3.909,
            bicarbonate: '52',
            _timestamp_ms: 1579604055529,
            sodium: '46.6',
            bicarbonateMeqL: 0.8522354792185657,
            name: 'Adelaide (Cumberland Park)',
            type: 'source',
            ionBalance: -1,
            alkalinity: 42.612,
            sulfate: '37.1',
            _rev: 'Rg52cM1Abxgb3eb9xs4N4RdielBPgJ',
            residualAlkalinityMeqLCalc: 0.37846,
            ionBalanceOff: true,
            _created: {
              _seconds: 1570932300,
              _nanoseconds: 775000000,
            },
            ph: '7.4',
            _id: 'NLjcLatA9F4swsYcOdHIw7VfeL1VFx',
            calcium: '18.8',
            _timestamp: {
              _seconds: 1579604055,
              _nanoseconds: 529000000,
            },
            hardness: 86,
            soClRatio: 0.46,
            residualAlkalinity: 23.63338,
          },
          mashPh: 5.24,
          mash: {
            magnesium: 9.44,
            ionBalance: 0,
            _created: {
              _seconds: 1570932300,
              _nanoseconds: 775000000,
            },
            ph: '7.4',
            ionBalanceOff: true,
            residualAlkalinityMeqLCalc: -2.26815,
            sodium: 46.6,
            anions: 11.316,
            type: 'source',
            _timestamp_ms: 1579604055529,
            cations: 11.153,
            sulfate: 392.846,
            soClRatio: 4.85,
            bicarbonateMeqL: 0.8522354792185657,
            hardness: 456,
            calcium: 167.299,
            chloride: 81,
            name: 'Adelaide (Cumberland Park)',
            _id: 'NLjcLatA9F4swsYcOdHIw7VfeL1VFx',
            residualAlkalinity: -82.43945,
            _timestamp: {
              _seconds: 1579604055,
              _nanoseconds: 529000000,
            },
            bicarbonate: 52,
            _rev: 'Rg52cM1Abxgb3eb9xs4N4RdielBPgJ',
            alkalinity: 42.612,
            _version: '1.10.1',
          },
          mashWaterAmount: null,
          target: {
            _timestamp_ms: 1592628227716,
            hardness: 348,
            cations: 7.666,
            bicarbonate: 33,
            description:
              'High sulfate with restrained chloride which helps accentuate hop bitterness/dryness. For hoppy American styles. Pale Ale, American Amber Ale, Brown Ale, IPA, Double IPA, Triple IPA, Imperial IPA, American Barleywine.',
            bicarbonateMeqL: 0.5408417464271666,
            chloride: 50,
            magnesium: 18,
            residualAlkalinityMeqLCalc: -1.68412,
            calcium: 110,
            type: 'target',
            _version: '2.3.0',
            alkalinity: 27.0423,
            sulfate: 275,
            soClRatio: 5.5,
            sodium: 16,
            name: 'Hoppy',
            residualAlkalinity: -62.1129,
            _id: 'default-hoppy',
            ionBalanceOff: false,
            _timestamp: {
              _seconds: 1592628227,
              _nanoseconds: 716000000,
            },
            ionBalance: 0,
            _rev: 'WDyxCYxrFNxZvIM0wqFFfxAmVUvKxC',
            _created: {
              _seconds: 1572178067,
              _nanoseconds: 206000000,
            },
            anions: 7.677,
          },
          settings: {
            calciumSulfate: {
              mash: true,
              sparge: true,
              auto: true,
            },
            sodiumBicarbonate: {
              sparge: false,
              auto: false,
              mash: true,
            },
            adjustSparge: true,
            magnesiumSulfate: {
              mash: false,
              sparge: false,
              auto: false,
            },
            calciumChloride: {
              form: 'dihydrate',
              auto: true,
              mash: true,
              sparge: true,
            },
            calciumHydroxide: {
              mash: false,
              auto: false,
              sparge: false,
            },
          },
          total: {
            _created: {
              _seconds: 1570932300,
              _nanoseconds: 775000000,
            },
            anions: 8.644,
            chloride: 81,
            name: 'Adelaide (Cumberland Park)',
            bicarbonate: 52,
            _rev: 'Rg52cM1Abxgb3eb9xs4N4RdielBPgJ',
            bicarbonateMeqL: 0.8522354792185657,
            ionBalance: 0,
            _timestamp: {
              _seconds: 1579604055,
              _nanoseconds: 529000000,
            },
            _version: '1.10.1',
            cations: 8.479,
            ph: '7.4',
            residualAlkalinity: -44.17583,
            ionBalanceOff: true,
            soClRatio: 3.27,
            sulfate: 264.518,
            _timestamp_ms: 1579604055529,
            sodium: 46.6,
            hardness: 322,
            _id: 'NLjcLatA9F4swsYcOdHIw7VfeL1VFx',
            type: 'source',
            residualAlkalinityMeqLCalc: -1.31344,
            calcium: 113.731,
            magnesium: 9.44,
            alkalinity: 42.612,
          },
          style: 'default-49',
          spargeAcidPhAdjustment: 0,
        },
        mash: {
          steps: [
            {
              name: '',
              type: 'Temperature',
              stepTemp: 65,
              stepTime: 60,
            },
            {
              name: 'Mash Out',
              stepTime: 10,
              stepTemp: 75,
              type: 'Temperature',
            },
          ],
          _id: 'default-hf-mo',
          name: 'High fermentability plus mash out',
        },
        sumDryHopPerLiter: 5.217391304347826,
        fgEstimated: 1.011,
        carbonationStyle: {
          carbMax: 2.9,
          name: 'American IPA',
          carbMin: 2.4,
          _id: '21A',
        },
        styleIbu: true,
        path: '',
        _timestamp: {
          _seconds: 1600564204,
          _nanoseconds: 577000000,
        },
        data: {
          hltWaterAmount: 11.5,
          mashVolume: 24.5675,
          mashFermentables: [
            {
              potentialPercentage: 82.23,
              costPerAmount: null,
              grainCategory: 'Base',
              amount: 6,
              manufacturingDate: null,
              userNotes: '',
              _id: 'default-4e694a1',
              percentage: 96,
              lovibond: 2.4,
              protein: null,
              substitutes: '',
              diastaticPower: null,
              name: 'Pale Malt, Traditional Ale',
              ibuPerAmount: null,
              origin: 'Australia',
              usedIn: '',
              supplier: 'Joe White Maltings',
              type: 'Grain',
              bestBeforeDate: null,
              moisture: null,
              notFermentable: false,
              attenuation: 0.81,
              notes: '',
              potential: 1.038,
              color: 2.538071,
              inventory: null,
            },
            {
              potential: 1.035,
              substitutes: '',
              color: 50.761421,
              amount: 0.25,
              type: 'Grain',
              percentage: 4,
              notes: '',
              bestBeforeDate: null,
              name: 'Caramel/Crystal Malt',
              usedIn: '',
              _id: 'default-a728cae',
              manufacturingDate: null,
              notFermentable: false,
              costPerAmount: null,
              userNotes: '',
              potentialPercentage: 75,
              diastaticPower: null,
              attenuation: 0.55,
              protein: null,
              lovibond: 38,
              supplier: 'Bairds',
              inventory: null,
              origin: 'UK',
              moisture: null,
              ibuPerAmount: null,
              grainCategory: 'Crystal/Caramel',
            },
          ],
          spargeWaterAmount: 11.5,
          totalWaterAmount: 31.88,
          mashFermentablesAmount: 6.25,
          mashWaterAmount: 20.38,
          hopsAmount: 200,
          otherFermentables: [],
          strikeTemp: null,
          mashVolumeSurplus: 0,
          otherFermentablesAmount: 0,
          topUpWater: 0,
        },
        tags: null,
        hopStandMinutes: 0,
        hops: [
          {
            ibu: 32,
            origin: 'US',
            _id: 'default-bc4774ae',
            time: 45,
            usage: 'Bittering',
            amount: 40,
            manufacturingDate: null,
            year: null,
            type: 'Pellet',
            userNotes: '',
            _editFlag: true,
            notes: '',
            substitutes: '',
            usedIn: '',
            temp: null,
            use: 'Boil',
            bestBeforeDate: null,
            name: 'Centennial',
            alpha: 8.8,
          },
          {
            origin: 'US',
            bestBeforeDate: null,
            year: null,
            _id: 'default-bc4774ae',
            type: 'Pellet',
            usage: 'Bittering',
            notes: '',
            name: 'Centennial',
            substitutes: '',
            amount: 40,
            ibu: 26.8,
            alpha: 8.8,
            use: 'Boil',
            time: 30,
            _editFlag: true,
            userNotes: '',
            temp: null,
            usedIn: '',
            manufacturingDate: null,
          },
          {
            ibu: 0,
            substitutes: '',
            timeUnit: 'days',
            usedIn: '',
            alpha: 8.8,
            bestBeforeDate: null,
            userNotes: '',
            temp: null,
            manufacturingDate: null,
            notes: '',
            amount: 120,
            time: 4,
            type: 'Pellet',
            actualTime: 1601428204911,
            usage: 'Bittering',
            origin: 'US',
            name: 'Centennial',
            _id: 'default-bc4774ae',
            year: null,
            day: 10,
            use: 'Dry Hop',
          },
        ],
        styleCarb: true,
        author: 'Andy',
        color: 7.1,
        defaults: {
          grainColor: 'default',
          altitude: 'm',
          color: 'ebc',
          volume: 'l',
          gravity: 'sg',
          weight: 'kg',
          hop: 'g',
          carbonation: 'vol',
          attenuation: 'normal',
          temp: 'c',
          abv: 'simple',
          ibu: 'tinseth',
          preferred: 'metric',
          pressure: 'psi',
        },
        styleOg: true,
        fermentables: [
          {
            inventory: null,
            substitutes: '',
            protein: null,
            _id: 'default-4e694a1',
            origin: 'Australia',
            supplier: 'Joe White Maltings',
            diastaticPower: null,
            userNotes: '',
            grainCategory: 'Base',
            percentage: 96,
            potentialPercentage: 82.23,
            notes: '',
            color: 2.538071,
            ibuPerAmount: null,
            notFermentable: false,
            name: 'Pale Malt, Traditional Ale',
            usedIn: '',
            bestBeforeDate: null,
            amount: 6,
            type: 'Grain',
            manufacturingDate: null,
            moisture: null,
            attenuation: 0.81,
            costPerAmount: null,
            potential: 1.038,
            lovibond: 2.4,
          },
          {
            bestBeforeDate: null,
            inventory: null,
            color: 50.761421,
            costPerAmount: null,
            supplier: 'Bairds',
            ibuPerAmount: null,
            lovibond: 38,
            origin: 'UK',
            name: 'Caramel/Crystal Malt',
            _id: 'default-a728cae',
            percentage: 4,
            potentialPercentage: 75,
            protein: null,
            notes: '',
            potential: 1.035,
            attenuation: 0.55,
            usedIn: '',
            substitutes: '',
            amount: 0.25,
            diastaticPower: null,
            type: 'Grain',
            moisture: null,
            manufacturingDate: null,
            notFermentable: false,
            userNotes: '',
            grainCategory: 'Crystal/Caramel',
          },
        ],
        yeast: {
          actualPacks: 2.777036920349187,
          millionCellsPerMl: 17,
          pitchRateActual: 1.02,
          startType: 'packages',
          cellsPerLiquidPkg: 100,
          packsPitchCells: 390,
          viability: 0.87,
          gramsPerDryPkg: 10,
          overbuildCells: null,
          starterPackages: 1,
          pitchRatePkg: 1.08,
          type: 'Dry',
          packs: 3,
          calcViablity: false,
          cellsPrGramDry: 13,
          pitchCells: 361.0147996453943,
          purePitch: false,
          gramsDry: 27.770369203491867,
          calcStarterVol: false,
          volume: 23,
          mode: 'starter',
          rehydrate: true,
          growthModel: 'braukaiser',
          manufacturingDate: 1598412622843,
          initCells: 130,
          rate: 1,
          og: 1.064105873,
          steps: [
            {
              starterNewCellCount: 405.79999999999995,
              starterPitchRate: 1.15,
              starterGramExtract: 197,
              startCells: 130,
              starterMillionCellsPerMl: 18,
              harvestRatio: null,
              starterPitchCellCount: null,
              startVol: 2,
              startGravity: 1.036,
              starterGramLiquidExtract: 240,
              growthFactor: 3.12,
              inoculationRate: 65,
            },
          ],
        },
        avgWeightedHopstandTemp: 80,
        fgFormula: 'normal',
        attenuation: 0.82,
        type: 'All Grain',
        hidden: false,
        boilTime: 60,
        abv: 6.96,
        efficiency: 75,
        batchSize: 23,
        fermentablesTotalAmount: 6.25,
        _init: true,
        styleAbv: true,
        fermentation: {
          name: 'Ale',
          _id: 'default',
          steps: [
            {
              stepTime: 14,
              type: 'Primary',
              stepTemp: 20,
            },
          ],
        },
        fermentableIbu: 0,
        styleRbr: true,
        yeastToleranceExceededBy: null,
        nutrition: {
          calories: {
            total: 60.46591005829747,
            alcohol: 40.03538069734636,
            kJ: 252.9893676839166,
            carbs: 20.430529360951102,
          },
          carbs: {
            total: 5.101560830518045,
          },
        },
      },
      measurements: [
        {
          text: '',
          timestamp: 1600564204924,
          status: 'Brewing',
        },
      ],
      measuredAbv: 6.7,
      measuredBoilSize: 29,
      _id: 'kSWOoYIfAPPF1EDs8wpB1IRyhoDLBK',
      _type: 'batch',
      tasteNotes:
        'I love Centennial. Delicious, hoppy aroma and flavour with nice solid malt to back it up. A solid IPA that I could drink a lot of and would make again in a heartbeat. Very happy with the recipe (obviously) and very happy with the execution.',
      brewer: 'Andy',
      batchHopsLocal: [],
      hidden: false,
      mashStepsCount: 2,
      batchFermentables: [
        {
          potential: 1.0345,
          color: 65,
          displayAmount: 0.25,
          totalCost: 0,
          name: 'Caramel/Crystal Malt',
          _id: 'default-a728cae',
          type: 'Grain',
          attenuation: 0.55,
          amount: 0.25,
          inventory: 0,
          origin: 'UK',
          notFermentable: null,
          supplier: 'Bairds',
          notInRecipe: false,
          costPerAmount: 0,
          potentialPercentage: 75,
          ibuPerAmount: null,
        },
        {
          inventory: 0,
          costPerAmount: 0,
          supplier: 'Joe White Maltings',
          notInRecipe: false,
          name: 'Pale Malt, Traditional Ale',
          notFermentable: null,
          displayAmount: 6,
          totalCost: 0,
          color: 3,
          attenuation: 0.81,
          origin: 'Australia',
          ibuPerAmount: null,
          potential: 1.0378258,
          type: 'Grain',
          _id: 'default-4e694a1',
          amount: 6,
          potentialPercentage: 82.23,
        },
      ],
      fermentationStartDate: 1600564204911,
      estimatedIbu: 59,
      estimatedFg: 1.012,
      batchYeasts: [
        {
          inventoryUnit: 'pkg',
          laboratory: "Mangrove Jack's",
          form: 'Dry',
          amount: 1,
          notInRecipe: false,
          name: 'US West Coast Yeast',
          _id: 'default-fc2796',
          displayAmount: 1,
          inventory: 0,
          costPerAmount: 0,
          productId: 'M44',
          fermentsAll: false,
          totalCost: 0,
          attenuation: 73,
          maxTemp: 23.3,
          type: 'Ale',
          minTemp: 15,
          flocculation: 'Medium',
          unit: 'pkg',
        },
      ],
      _init: true,
      boilSteps: [
        {
          name: 'Centennial',
          time: 45,
        },
        {
          name: 'Centennial',
          time: 30,
        },
      ],
      tasteRating: 91,
      name: 'Batch',
      _timestamp_ms: 1603105211188,
      devices: {
        myBrewbot: {
          items: [],
          enabled: true,
        },
        iSpindel: {
          enabled: true,
          items: [],
        },
        plaatoAirlock: {
          items: [],
          enabled: true,
        },
        plaatoKeg: {
          items: [],
          enabled: true,
        },
        tilt: {
          gravity: true,
          items: [],
          mode: 'default',
          enabled: true,
          temp: true,
        },
        brewPiLess: {
          items: [],
          enabled: true,
        },
        gfcc: {
          brewDeviceId: null,
          enabled: false,
          items: [],
        },
        stream: {
          enabled: true,
          items: [],
        },
        smartPid: {
          brewDeviceId: null,
          items: [],
          enabled: false,
        },
      },
      carbonationType: 'Keg (Force)',
      _archived: false,
      batchYeastsLocal: [],
      status: 'Completed',
      batchHops: [
        {
          notInRecipe: false,
          inventory: 0,
          type: 'Pellet',
          origin: 'US',
          costPerAmount: 0,
          alpha: 8.8,
          _id: 'default-bc4774ae',
          displayAmount: 200,
          name: 'Centennial',
          totalCost: 0,
          usage: 'Bittering',
          amount: 200,
        },
      ],
      measuredMashEfficiency: 81.1,
      primingSugarEquiv: null,
      measuredConversionEfficiency: null,
      boilStepsCount: 2,
    },
    {
      _init: true,
      brewDate: 1599871212560,
      measuredAbv: 4.6,
      devices: {
        plaatoAirlock: {
          enabled: true,
          items: [],
        },
        iSpindel: {
          enabled: true,
          items: [],
        },
        tilt: {
          items: [],
          gravity: true,
          mode: 'default',
          enabled: true,
          temp: true,
        },
        myBrewbot: {
          items: [],
          enabled: true,
        },
        stream: {
          enabled: true,
          items: [],
        },
        brewPiLess: {
          items: [],
          enabled: true,
        },
        plaatoKeg: {
          enabled: true,
          items: [],
        },
        gfcc: {
          items: [],
          brewDeviceId: null,
          enabled: false,
        },
        smartPid: {
          enabled: false,
          brewDeviceId: null,
          items: [],
        },
      },
      mashStepsCount: 2,
      measuredFg: 1.011,
      estimatedRbRatio: 0.67,
      primingSugarEquiv: null,
      _type: 'batch',
      _version: '2.4.6',
      batchNotes: '',
      status: 'Completed',
      measuredKettleSize: 25,
      measuredKettleEfficiency: 78.44,
      carbonationType: 'Keg (Force)',
      tasteNotes:
        'A light very drinkable beer. Sweet biscuit maltiness, but remains dry on the finish. Hops are earthy and subtle—this is all about the malt. Very slight fruitiness from the yeast, but clean overall. A quite malty but drinkable beer that’s a nice change from the big hop bombs I’ve had recently.',
      measuredAttenuation: 75.4,
      measuredOg: 1.046,
      _id: 'HIjp3bIHYBz5YB1Sj4amPPbjncIzmV',
      brewControllerEnabled: false,
      boilStepsCount: 3,
      measuredBoilSize: 28,
      batchHops: [
        {
          origin: 'United Kingdom',
          _id: 'default-7f820fa1',
          alpha: 4,
          usage: 'Both',
          notInRecipe: false,
          totalCost: 0,
          inventory: 0,
          displayAmount: 70,
          type: 'Pellet',
          name: 'East Kent Goldings (EKG)',
          costPerAmount: 0,
          amount: 70,
        },
        {
          name: 'Magnum',
          type: 'Pellet',
          costPerAmount: 0,
          _id: 'default-66c7ffab',
          alpha: 10.7,
          origin: 'US',
          displayAmount: 10,
          amount: 10,
          inventory: 0,
          notInRecipe: false,
          usage: 'Bittering',
          totalCost: 0,
        },
      ],
      name: 'Batch',
      recipe: {
        styleFg: true,
        type: 'All Grain',
        ibu: 31.4,
        sumDryHopPerLiter: 0,
        ogPlato: 11.4,
        efficiency: 75,
        mash: {
          name: 'High fermentability plus mash out',
          _id: 'default-hf-mo',
          steps: [
            {
              type: 'Temperature',
              stepTime: 60,
              name: '',
              stepTemp: 65,
            },
            {
              name: 'Mash Out',
              stepTime: 10,
              type: 'Temperature',
              stepTemp: 75,
            },
          ],
        },
        _type: 'recipe',
        fermentation: {
          name: 'Ale',
          _id: 'default',
          steps: [
            {
              stepTemp: 20,
              stepTime: 14,
              type: 'Primary',
            },
          ],
        },
        rbRatio: 0.69,
        boilTime: 60,
        styleColor: true,
        primaryTemp: 20,
        defaults: {
          pressure: 'psi',
          altitude: 'm',
          abv: 'simple',
          volume: 'l',
          hop: 'g',
          preferred: 'metric',
          attenuation: 'normal',
          carbonation: 'vol',
          ibu: 'tinseth',
          temp: 'c',
          grainColor: 'default',
          gravity: 'sg',
          color: 'ebc',
          weight: 'kg',
        },
        _public: false,
        fermentables: [
          {
            notFermentable: false,
            substitutes: '',
            usedIn: '',
            ibuPerAmount: null,
            inventory: null,
            origin: 'New Zealand',
            attenuation: 0.81,
            grainCategory: 'Base',
            protein: null,
            diastaticPower: null,
            notes: '',
            moisture: null,
            percentage: 100,
            supplier: 'Gladfield',
            _id: 'default-8ea92ed',
            color: 3.045685,
            potential: 1.037,
            userNotes: '',
            costPerAmount: null,
            type: 'Grain',
            amount: 4.5,
            name: 'Ale Malt',
            potentialPercentage: 81.4,
          },
        ],
        public: false,
        _init: true,
        name: 'British Golden Ale',
        yeasts: [
          {
            userNotes: '',
            maxTemp: 20,
            name: 'SafAle English Ale',
            flocculation: 'Medium',
            laboratory: 'Fermentis',
            productId: 'S-04',
            _id: 'default-e294c5',
            form: 'Dry',
            type: 'Ale',
            description:
              'English ale yeast selected for its fast fermentation character and its ability to form a compact sediment at the end of fermentation, helping to improve beer clarity. Recommended for the production of a large range of ales and specially adapted to cask-conditioned ones and fermentation in cylindo-conical tanks.',
            attenuation: 78,
            minTemp: 15,
            manufacturingDate: null,
            fermentsAll: false,
            amount: 1,
            maxAbv: null,
            unit: 'pkg',
          },
        ],
        preBoilGravity: 1.041,
        hopsTotalAmount: 80,
        carbonation: 2.4,
        ibuFormula: 'tinseth',
        style: {
          abvMin: 3.8,
          lovibondMin: 2,
          category: 'Pale Commonwealth Beer',
          rbrMax: 1.02,
          colorMin: 2,
          type: 'Pale Ale',
          fgMax: 1.012,
          colorMax: 6,
          styleLetter: 'A',
          name: 'British Golden Ale',
          ibuMax: 45,
          ogMin: 1.038,
          buGuMin: 0.44,
          styleGuide: 'BJCP 2015',
          rbrMin: 0.45,
          ogMax: 1.053,
          buGuMax: 0.99,
          carbonationStyle: '12A',
          abvMax: 5,
          categoryNumber: '12',
          ibuMin: 20,
          lovibondMax: 6,
          fgMin: 1.006,
          _id: 'default-37',
        },
        styleIbu: true,
        path: '',
        boilSize: 28,
        styleAbv: true,
        mashEfficiency: 78.3,
        fermentablesTotalAmount: 4.5,
        tags: null,
        _rev: 'OWeikmiysR4qIyYHoJDrrS5T79jIcd',
        miscs: [
          {
            unit: 'g',
            time: null,
            name: 'Baking Soda (NaHCO3)',
            _id: 'default-2302b0',
            type: 'Water Agent',
            waterAdjustment: true,
            use: 'Mash',
            timeIsDays: false,
            amount: 3,
          },
          {
            _id: 'default-3b1827',
            timeIsDays: false,
            type: 'Water Agent',
            amount: 5.84,
            use: 'Mash',
            concentration: null,
            unit: 'g',
            waterAdjustment: true,
            name: 'Calcium Chloride (CaCl2)',
            time: null,
          },
          {
            unit: 'g',
            type: 'Water Agent',
            use: 'Mash',
            time: null,
            name: 'Gypsum (CaSO4)',
            _id: 'default-1f88df',
            waterAdjustment: true,
            timeIsDays: false,
            amount: 9.74,
          },
          {
            _id: 'default-07adb1',
            waterAdjustment: true,
            timeIsDays: false,
            name: 'Lactic Acid',
            unit: 'ml',
            amount: 4,
            use: 'Mash',
            time: null,
            type: 'Water Agent',
            concentration: 85,
          },
          {
            amount: 1,
            notes: '',
            _id: 'default-ff4911',
            time: null,
            type: 'Water Agent',
            amountPerL: null,
            userNotes: '',
            unit: 'items',
            use: 'Mash',
            substitutes: '',
            name: 'Campden Tablets',
            timeIsDays: false,
          },
          {
            amountPerL: null,
            unit: 'items',
            timeIsDays: false,
            _id: 'default-8mv12',
            type: 'Fining',
            notes: '',
            amount: 1,
            userNotes: '',
            use: 'Boil',
            substitutes: '',
            name: 'Whirlfloc',
            time: 5,
          },
        ],
        styleRbr: true,
        buGuRatio: 0.68,
        searchTags: [],
        postBoilGravity: 1.045851603,
        hidden: false,
        carbonationStyle: {
          name: 'British Golden Ale',
          carbMin: 2,
          _id: '12A',
          carbMax: 2.8,
        },
        _id: 'WXPHr0btbHcOklkcaDMJDoLjSIeqP9',
        og: 1.045851603,
        styleCarb: true,
        hopStandMinutes: 20,
        water: {
          spargeAdjustments: {
            sodiumMetabisulfitePPM: 0,
            bicarbonate: 0,
            calcium: 0,
            sodium: 0,
            sulfate: 0,
            chloride: 0,
            acids: [
              {
                concentration: '85',
                amount: 0,
                type: 'lactic',
              },
            ],
            magnesium: 0,
            volume: 14.83,
          },
          mashAdjustments: {
            calciumChloride: 5.84,
            bicarbonate: 136.198,
            sodiumMetabisulfitePPM: 0,
            calcium: 246.611,
            sulfate: 347.093,
            calciumSulfate: 9.74,
            magnesiumSulfate: 0,
            acids: [
              {
                alkalinityMeqL: -3.7664919390159,
                type: 'lactic',
                concentration: '85',
                amount: 4,
              },
            ],
            magnesiumChloride: 0,
            sodiumMetabisulfite: 0,
            chloride: 179.976,
            sodiumBicarbonate: 3,
            calciumCarbonate: 0,
            magnesium: 0,
            sodium: 52.466,
            calciumHydroxide: 0,
            volume: 15.65,
            sodiumChloride: 0,
          },
          acidPhAdjustment: -0.32275,
          target: {
            ionBalance: 0,
            chloride: 9.6,
            hardness: 171,
            residualAlkalinity: 60.2297,
            magnesium: 10,
            sulfate: 65,
            ionBalanceOff: false,
            soClRatio: 6.77,
            residualAlkalinityMeqLCalc: 0.99133,
            _timestamp_ms: 1587427760764,
            _timestamp: {
              _seconds: 1587427760,
              _nanoseconds: 764000000,
            },
            sodium: 6.2,
            type: 'target',
            _created: {
              _seconds: 1587427760,
              _nanoseconds: 764000000,
            },
            _rev: 'Caw8UWNZp9Fg60p8A5CEZ4BXSM2WfK',
            anions: 3.689,
            alkalinity: 103.2523,
            name: 'English Ale',
            bicarbonate: 126,
            _id: 'default-englishale',
            _version: '2.1.6',
            bicarbonateMeqL: 2.065032122721909,
            calcium: 52,
            cations: 3.688,
          },
          enableSpargeAdjustments: false,
          mash: {
            magnesium: 9.44,
            ionBalance: 0,
            _timestamp: {
              _seconds: 1579604055,
              _nanoseconds: 529000000,
            },
            cations: 18.331,
            _id: 'NLjcLatA9F4swsYcOdHIw7VfeL1VFx',
            soClRatio: 1.47,
            _version: '1.10.1',
            ph: '7.4',
            alkalinity: 154.2212,
            name: 'Adelaide (Cumberland Park)',
            bicarbonate: 188.198,
            sulfate: 384.193,
            hardness: 701,
            type: 'source',
            residualAlkalinity: -40.91165,
            residualAlkalinityMeqLCalc: -1.78457,
            bicarbonateMeqL: 3.0844040907303003,
            sodium: 99.066,
            _created: {
              _seconds: 1570932300,
              _nanoseconds: 775000000,
            },
            anions: 18.445,
            ionBalanceOff: true,
            chloride: 260.976,
            calcium: 265.411,
            _rev: 'Rg52cM1Abxgb3eb9xs4N4RdielBPgJ',
            _timestamp_ms: 1579604055529,
          },
          totalTargetDiff: {
            sulfate: 150.315,
            residualAlkalinityMeqLCalc: -1.72348,
            residualAlkalinity: -69.73722,
            cations: 7.545,
            bicarbonateMeqL: -0.06668742624885277,
            sodium: 67.339,
            bicarbonate: -4.069,
            ionBalanceOff: true,
            calcium: 93.423,
            ionBalance: 0,
            soClRatio: 0.92,
            magnesium: -0.56,
            hardness: 231,
            alkalinity: -3.3344,
            anions: 7.683,
            chloride: 163.809,
          },
          totalAdjustments: {
            magnesium: 0,
            calcium: 126.623,
            calciumChloride: 5.84,
            sodiumMetabisulfite: 0,
            magnesiumSulfate: 0,
            bicarbonate: 69.931,
            sodiumMetabisulfitePPM: 0,
            calciumSulfate: 9.74,
            volume: 30.48,
            magnesiumChloride: 0,
            sulfate: 178.215,
            acids: [
              {
                type: 'lactic',
                amount: 4,
                concentration: '85',
                alkalinityMeqL: -3.7664919390159,
              },
            ],
            sodiumChloride: 0,
            chloride: 92.409,
            sodium: 26.939,
            calciumCarbonate: 0,
            calciumHydroxide: 0,
            sodiumBicarbonate: 3,
          },
          spargeAcidPhAdjustment: 0,
          sourceTargetDiff: {
            ionBalance: -30,
            sodium: 40.4,
            calcium: -33.2,
            magnesium: -0.56,
            sulfate: -27.9,
            soClRatio: -0.39,
            cations: 0.055,
            hardness: -85,
            residualAlkalinity: -36.59622,
            chloride: 71.4,
            bicarbonate: -74,
            residualAlkalinityMeqLCalc: -0.61286,
            bicarbonateMeqL: -1.2127966435033435,
            anions: 0.22,
            ionBalanceOff: true,
            alkalinity: -60.6402,
          },
          sparge: {
            ionBalance: -1,
            hardness: 86,
            _created: {
              _seconds: 1570932300,
              _nanoseconds: 775000000,
            },
            alkalinity: 42.612,
            bicarbonate: 52,
            residualAlkalinityMeqLCalc: 0.37846,
            anions: 3.909,
            calcium: 18.8,
            soClRatio: 0.46,
            sodium: 46.6,
            _rev: 'Rg52cM1Abxgb3eb9xs4N4RdielBPgJ',
            type: 'source',
            _timestamp_ms: 1579604055529,
            ionBalanceOff: true,
            residualAlkalinity: 23.63338,
            _timestamp: {
              _seconds: 1579604055,
              _nanoseconds: 529000000,
            },
            name: 'Adelaide (Cumberland Park)',
            chloride: 81,
            sulfate: 37.1,
            _id: 'NLjcLatA9F4swsYcOdHIw7VfeL1VFx',
            ph: '7.4',
            cations: 3.742,
            magnesium: 9.44,
            _version: '1.10.1',
            bicarbonateMeqL: 0.8522354792185657,
          },
          mashTargetDiff: {
            alkalinity: 50.9689,
            sodium: 92.866,
            hardness: 530,
            chloride: 251.376,
            magnesium: -0.56,
            bicarbonate: 62.198,
            cations: 14.643,
            ionBalance: 0,
            calcium: 213.411,
            residualAlkalinity: -101.14135,
            anions: 14.755,
            residualAlkalinityMeqLCalc: -2.77589,
            soClRatio: 1.27,
            ionBalanceOff: true,
            sulfate: 319.193,
            bicarbonateMeqL: 1.0193719680083912,
          },
          enableAcidAdjustments: true,
          mashPhDistilled: 5.68,
          source: {
            sodium: '46.6',
            alkalinity: 42.612,
            chloride: '81',
            residualAlkalinityMeqLCalc: 0.37846,
            cations: 3.742,
            _created: {
              _seconds: 1570932300,
              _nanoseconds: 775000000,
            },
            residualAlkalinity: 23.63338,
            magnesium: '9.44',
            bicarbonateMeqL: 0.8522354792185657,
            bicarbonate: '52',
            _rev: 'Rg52cM1Abxgb3eb9xs4N4RdielBPgJ',
            ph: '7.4',
            ionBalanceOff: true,
            _timestamp_ms: 1579604055529,
            _version: '1.10.1',
            hardness: 86,
            soClRatio: 0.46,
            name: 'Adelaide (Cumberland Park)',
            type: 'source',
            calcium: '18.8',
            ionBalance: -1,
            sulfate: '37.1',
            _timestamp: {
              _seconds: 1579604055,
              _nanoseconds: 529000000,
            },
            _id: 'NLjcLatA9F4swsYcOdHIw7VfeL1VFx',
            anions: 3.909,
          },
          settings: {
            calciumChloride: {
              form: 'dihydrate',
              mash: true,
              auto: true,
              sparge: true,
            },
            sodiumBicarbonate: {
              sparge: false,
              auto: false,
              mash: true,
            },
            calciumSulfate: {
              sparge: true,
              auto: true,
              mash: true,
            },
            calciumHydroxide: {
              sparge: false,
              auto: false,
              mash: false,
            },
            magnesiumSulfate: {
              mash: false,
              sparge: false,
              auto: false,
            },
            adjustSparge: true,
          },
          mashPh: 5.21,
          spargeWaterAmount: null,
          spargeTargetDiff: {
            sulfate: -27.9,
            residualAlkalinity: -36.59622,
            bicarbonateMeqL: -1.2127966435033435,
            alkalinity: -60.6402,
            magnesium: -0.56,
            ionBalanceOff: true,
            anions: 0.22,
            ionBalance: -30,
            calcium: -33.2,
            sodium: 40.4,
            cations: 0.055,
            soClRatio: -0.39,
            residualAlkalinityMeqLCalc: -0.61286,
            hardness: -85,
            bicarbonate: -74,
            chloride: 71.4,
          },
          total: {
            hardness: 401,
            soClRatio: 1.24,
            residualAlkalinity: -9.50752,
            alkalinity: 99.9179,
            anions: 11.372,
            magnesium: 9.44,
            _rev: 'Rg52cM1Abxgb3eb9xs4N4RdielBPgJ',
            _version: '1.10.1',
            ionBalance: 0,
            chloride: 173.409,
            residualAlkalinityMeqLCalc: -0.73215,
            type: 'source',
            bicarbonateMeqL: 1.9983446964730562,
            ph: '7.4',
            _timestamp_ms: 1579604055529,
            name: 'Adelaide (Cumberland Park)',
            bicarbonate: 121.931,
            ionBalanceOff: true,
            sodium: 73.539,
            cations: 11.233,
            sulfate: 215.315,
            calcium: 145.423,
            _created: {
              _seconds: 1570932300,
              _nanoseconds: 775000000,
            },
            _id: 'NLjcLatA9F4swsYcOdHIw7VfeL1VFx',
            _timestamp: {
              _seconds: 1579604055,
              _nanoseconds: 529000000,
            },
          },
          mashWaterAmount: null,
          style: 'default',
        },
        styleConformity: true,
        hops: [
          {
            time: 60,
            amount: 10,
            name: 'Magnum',
            use: 'Boil',
            year: null,
            temp: null,
            origin: 'US',
            _id: 'default-66c7ffab',
            notes: '',
            type: 'Pellet',
            usage: 'Bittering',
            usedIn: '',
            substitutes: '',
            ibu: 12.6,
            userNotes: '',
            alpha: 10.7,
          },
          {
            usedIn: '',
            alpha: 4,
            substitutes: '',
            time: 25,
            type: 'Pellet',
            notes: '',
            ibu: 12.9,
            name: 'East Kent Goldings (EKG)',
            amount: 35,
            temp: null,
            use: 'Boil',
            _editFlag: true,
            _id: 'default-7f820fa1',
            year: null,
            userNotes: '',
            origin: 'United Kingdom',
            usage: 'Both',
          },
          {
            substitutes: '',
            temp: 90,
            _id: 'default-7f820fa1',
            usedIn: '',
            type: 'Pellet',
            userNotes: '',
            amount: 35,
            use: 'Aroma',
            time: 20,
            notes: '',
            origin: 'United Kingdom',
            usage: 'Both',
            alpha: 5,
            name: 'East Kent Goldings (EKG)',
            _editFlag: true,
            year: null,
            timeUnit: null,
            ibu: 5.9,
          },
        ],
        abv: 4.73,
        fg: 1.01,
        fgFormula: 'normal',
        _version: '2.4.0',
        color: 4.4,
        batchSize: 23,
        nutrition: {
          calories: {
            carbs: 16.24817407397306,
            alcohol: 26.325050190950044,
            total: 42.573224264923105,
            kJ: 178.12637032443828,
          },
          carbs: {
            total: 4.101945221536867,
          },
        },
        fermentableIbu: 0,
        fgEstimated: 1.01,
        firstWortGravity: null,
        attenuation: 0.776,
        avgWeightedHopstandTemp: 90,
        styleBuGu: true,
        _created: {
          _seconds: 1592628324,
          _nanoseconds: 980000000,
        },
        styleOg: true,
        author: 'Andy',
        data: {
          hltWaterAmount: 14.83,
          otherFermentablesAmount: 0,
          mashVolume: 18.665,
          mashFermentables: [
            {
              potentialPercentage: 81.4,
              amount: 4.5,
              potential: 1.037,
              percentage: 100,
              color: 3.045685,
              attenuation: 0.81,
              moisture: null,
              costPerAmount: null,
              protein: null,
              notFermentable: false,
              usedIn: '',
              ibuPerAmount: null,
              name: 'Ale Malt',
              origin: 'New Zealand',
              substitutes: '',
              inventory: null,
              type: 'Grain',
              userNotes: '',
              _id: 'default-8ea92ed',
              notes: '',
              supplier: 'Gladfield',
              grainCategory: 'Base',
              diastaticPower: null,
            },
          ],
          hopsAmount: 80,
          spargeWaterAmount: 14.83,
          mashVolumeSurplus: 0,
          strikeTemp: null,
          otherFermentables: [],
          mashWaterAmount: 15.65,
          topUpWater: 0,
          mashFermentablesAmount: 4.5,
          totalWaterAmount: 30.48,
        },
        yeastToleranceExceededBy: null,
        _timestamp_ms: 1599871212238,
        equipment: {
          _created: {
            _seconds: 1592619686,
            _nanoseconds: 267000000,
          },
          mashTunDeadSpace: 3.5,
          waterGrainRatio: 2.7,
          name: 'Grainfather',
          mashTunLoss: 0,
          postBoilKettleVol: 25,
          boilSize: 28,
          spargeWaterFormula:
            'BoilVolumeColdL - MashWaterL + (GrainAmountKg * GrainAbsorptionRate) + MashTunLossL',
          hopstandTemperature: 80,
          calcMashEfficiency: true,
          _version: '2.3.0',
          _rev: 'm1hvhDZFHMhhDL7VSy9s3SqHecyakk',
          grainAbsorptionRate: 0.8,
          aromaHopUtilization: 0.23,
          fermenterLossEstimate: 0,
          batchSize: 23,
          hopUtilization: 1,
          fermenterVolumeBeforeTopUp: 23,
          boilTime: 60,
          calcBoilVolume: true,
          calcAromaHopUtilization: true,
          mashWaterVolumeLimitEnabled: true,
          mashWaterMax: 30,
          evaporationRate: 0.10714285714285714,
          efficiency: 75,
          _id: 'default-gf23',
          spargeWaterOverflow: 'Top-Up',
          efficiencyType: 'Fermenter',
          _timestamp: {
            _seconds: 1592619686,
            _nanoseconds: 267000000,
          },
          trubChillerLoss: 1,
          waterCalculation: 'Default_2',
          fermenterVolume: 23,
          _timestamp_ms: 1592619686267,
          mashEfficiency: 78.3,
          boilOffPerHr: 3,
          bottlingVolume: 21,
          mashWaterFormula: '(GrainAmountKg * WaterGrainRatio) + MashTunDeadSpaceL',
          fermenterLoss: 2,
        },
        _timestamp: {
          _seconds: 1599871212,
          _nanoseconds: 238000000,
        },
      },
      measuredMashEfficiency: 78.3,
      cost: {
        miscsShare: 0,
        hops: 0,
        fermentables: 0,
        total: 0,
        fermentablesShare: 0,
        hopsShare: 0,
        miscs: 0,
        yeastsShare: 0,
        yeasts: 0,
        perBottlingLiter: 0,
      },
      batchFermentables: [
        {
          attenuation: 0.81,
          displayAmount: 4.5,
          amount: 4.5,
          notFermentable: null,
          type: 'Grain',
          name: 'Ale Malt',
          potentialPercentage: 81.4,
          notInRecipe: false,
          _id: 'default-8ea92ed',
          color: 3.0456853,
          potential: 1.037444,
          totalCost: 0,
          costPerAmount: 0,
          supplier: 'Gladfield',
          inventory: 0,
          ibuPerAmount: null,
          origin: 'New Zealand',
        },
      ],
      estimatedOg: 1.046,
      measurements: [
        {
          text: '',
          timestamp: 1599871212562,
          status: 'Brewing',
        },
      ],
      fermentationControllerEnabled: false,
      carbonationForce: 10.8,
      _created: {
        _seconds: 1599871232,
        _nanoseconds: 795000000,
      },
      notes: [
        {
          type: 'statusChanged',
          status: 'Completed',
          timestamp: 1601779244356,
          note: '',
        },
        {
          status: 'Conditioning',
          timestamp: 1601087878125,
          type: 'statusChanged',
          note: '',
        },
        {
          timestamp: 1600747859310,
          status: 'Fermenting',
          note: 'Cold crashing in the fermenter because there’s space in the kegerator.',
        },
        {
          timestamp: 1599885767135,
          type: 'statusChanged',
          note: '',
          status: 'Fermenting',
        },
        {
          note: 'Added 18L strike water, so reduced sparge volume to 13L',
          status: 'Brewing',
          timestamp: 1599871395679,
        },
        {
          timestamp: 1599871231538,
          type: 'statusChanged',
          status: 'Brewing',
          note: '',
        },
      ],
      batchNo: 17,
      measuredBatchSize: 23,
      measuredEfficiency: 75.24,
      boilSteps: [
        {
          name: 'Magnum',
          time: 60,
        },
        {
          time: 25,
          name: 'East Kent Goldings (EKG)',
        },
        {
          name: 'Whirlfloc',
          time: 5,
        },
      ],
      hidden: false,
      _archived: false,
      batchHopsLocal: [],
      estimatedBuGuRatio: 0.68,
      tasteRating: 71,
      batchFermentablesLocal: [],
      batchYeastsLocal: [],
      _timestamp: {
        _seconds: 1602334829,
        _nanoseconds: 805000000,
      },
      _timestamp_ms: 1602334829805,
      bottlingDate: 1601080812560,
      estimatedFg: 1.011,
      estimatedIbu: 31,
      brewer: 'Andy',
      measuredConversionEfficiency: null,
      batchMiscs: [
        {
          _id: 'default-1f88df',
          displayAmount: 9.74,
          notInRecipe: false,
          use: 'Mash',
          costPerAmount: 0,
          inventory: 0,
          amount: 9.74,
          totalCost: 0,
          time: null,
          type: 'Water Agent',
          waterAdjustment: true,
          name: 'Gypsum (CaSO4)',
          timeIsDays: false,
          unit: 'g',
          inventoryUnit: 'g',
        },
        {
          displayAmount: 5.84,
          notInRecipe: false,
          _id: 'default-3b1827',
          costPerAmount: 0,
          time: null,
          inventoryUnit: 'g',
          inventory: 0,
          waterAdjustment: true,
          unit: 'g',
          use: 'Mash',
          totalCost: 0,
          amount: 5.84,
          timeIsDays: false,
          name: 'Calcium Chloride (CaCl2)',
          type: 'Water Agent',
        },
        {
          type: 'Water Agent',
          amount: 3,
          time: null,
          use: 'Mash',
          name: 'Baking Soda (NaHCO3)',
          waterAdjustment: true,
          unit: 'g',
          totalCost: 0,
          notInRecipe: false,
          displayAmount: 3,
          inventoryUnit: 'g',
          timeIsDays: false,
          costPerAmount: 0,
          inventory: 0,
          _id: 'default-2302b0',
        },
        {
          inventory: 0,
          waterAdjustment: true,
          timeIsDays: false,
          totalCost: 0,
          type: 'Water Agent',
          time: null,
          name: 'Lactic Acid',
          _id: 'default-07adb1',
          use: 'Mash',
          costPerAmount: 0,
          notInRecipe: false,
          unit: 'ml',
          inventoryUnit: 'ml',
          displayAmount: 4,
          amount: 4,
        },
        {
          displayAmount: 1,
          use: 'Mash',
          _id: 'default-ff4911',
          notInRecipe: false,
          inventoryUnit: 'items',
          amount: 1,
          unit: 'items',
          time: 60,
          type: 'Water Agent',
          timeIsDays: false,
          totalCost: 0,
          inventory: 0,
          costPerAmount: 0,
          name: 'Campden Tablets',
        },
        {
          name: 'Whirlfloc',
          type: 'Fining',
          inventory: 0,
          costPerAmount: 0,
          amount: 1,
          _id: 'default-8mv12',
          displayAmount: 1,
          totalCost: 0,
          use: 'Boil',
          time: 15,
          inventoryUnit: 'items',
          timeIsDays: false,
          unit: 'items',
          notInRecipe: false,
        },
      ],
      _rev: 'WtJxO5RdaW6Z8E68MxPERxnMTytT8B',
      batchYeasts: [
        {
          laboratory: 'Fermentis',
          description:
            'English ale yeast selected for its fast fermentation character and its ability to form a compact sediment at the end of fermentation, helping to improve beer clarity. Recommended for the production of a large range of ales and specially adapted to cask-conditioned ones and fermentation in cylindo-conical tanks.',
          form: 'Dry',
          totalCost: 0,
          flocculation: 'Medium',
          _id: 'default-e294c5',
          name: 'SafAle English Ale',
          notInRecipe: false,
          attenuation: 75,
          unit: 'pkg',
          maxTemp: 20,
          inventoryUnit: 'pkg',
          productId: 'S-04',
          amount: 1,
          fermentsAll: false,
          inventory: 0,
          costPerAmount: 0,
          displayAmount: 1,
          type: 'Ale',
          minTemp: 15,
        },
      ],
      estimatedColor: 4.4,
      batchMiscsLocal: [],
      fermentationStartDate: 1599871212560,
    },
  ]
}
